export const GET_RANDOM_QUOTE = 'GET_RANDOM_QUOTE';
export const GET_RANDOM_QUOTE_SUCCESS = 'GET_RANDOM_QUOTE_SUCCESS';
export const GET_RANDOM_QUOTE_FAILURE = 'GET_RANDOM_QUOTE_FAILURE';

export const GET_RANDOM_USER_DETAILS = 'GET_RANDOM_USER_DETAILS';
export const GET_RANDOM_USER_DETAILS_SUCCESS = 'GET_RANDOM_USER_DETAILS_SUCCESS';
export const GET_RANDOM_USER_DETAILS_FAILURE = 'GET_RANDOM_USER_DETAILS_FAILURE';